name: Run ESLint on Pull Requests

on:
  - push

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository

      - uses: actions/checkout@v1

      - name: npm install
          run: |
            make install
      - name: run linter
          run: |
            make lint